shopware:
  image: ffuenf/shopware
  restart: always
  volumes_from:
    - data
  volumes:
    - ./logs:/var/log/apache2
  links:
   - db
  ports:
   - "80:80"
   - "443:443"
  environment:
      SERVERNAME: ${SERVERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SHOPWARE_VERSION: ${SHOPWARE_VERSION}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

db:
    image: mysql:5.7
    restart: always
    ports:
        - "3307:3307"
    volumes_from:
        - dbdata
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}

dbdata:
  image: cogniteev/echo
  command: echo 'Database Data Container'
  volumes:
    - /var/lib/mysql

data:
  image: cogniteev/echo
  command: echo 'Data Container'
  volumes:
    - ./public:/var/www/html
